name: vnl-test
channels:
  - conda-forge
  - anaconda
  - menpo
dependencies:
  - opencv
  - python=3.11
  - numpy<2.0
  - matplotlib
  - pandas
  - pip
  - glew
  - mesalib
  - mesa-libgl-cos6-x86_64
  - glfw3
  - ipykernel
  - pip: 
    - -r requirements.txt 

#variables:             # Set MuJoCo environment variables
#  MUJOCO_GL: osmesa
#  PYOPENGL_PLATFORM: osmesa