MJCF_PATH: "/root/vast/rusham/GitRepos/stac-keypoints-ui/stac_keypoints_ui/data/sungaya_inexpectata_box.xml"

# Tolerance for the optimizations of the full model, limb, and root. 
# TODO: Re-implement optimizer loops to use these tolerances
FTOL: 1.0e-50
ROOT_FTOL: 1.0e-48
LIMB_FTOL: 1.0e-49

# Number of alternating pose and offset optimization rounds. 
N_ITERS: 10

KEYPOINT_INITIAL_OFFSETS:
  mouth: 0.0 0.0 0.0
  head: 0.0 0.0 0.0
  head_t1: 0.0 0.0 0.0
  t1_t2: 0.0 0.0 0.0
  t2_t3: 0.0 0.0 0.0
  t3_a1: 0.0 0.0 0.0
  a2_a3: 0.0 0.0 0.0
  a4_a5: 0.0 0.0 0.0
  a6_a7: 0.0 0.0 0.0
  a8_end: 0.0 0.0 0.0
  r_antenna_base: 0.0 0.0 0.0
  r_antenna_tip: 0.0 0.0 0.0
  l_antenna_base: 0.0 0.0 0.0
  l_antenna_tip: 0.0 0.0 0.0
  f_l_coxa: 0.0 0.0 0.0
  f_l_trochanter: 0.0 0.0 0.0
  f_l_femur: 0.0 0.0 0.0
  f_l_tibia: 0.0 0.0 0.0
  f_l_tarsus: 0.0 0.0 0.0
  f_l_claws: 0.0 0.0 0.0
  f_r_coxa: 0.0 0.0 0.0
  f_r_trochanter: 0.0 0.0 0.0
  f_r_femur: 0.0 0.0 0.0
  f_r_tibia: 0.0 0.0 0.0
  f_r_tarsus: 0.0 0.0 0.0
  f_r_claws: 0.0 0.0 0.0
  m_l_coxa: 0.0 0.0 0.0
  m_l_trochanter: 0.0 0.0 0.0
  m_l_femur: 0.0 0.0 0.0
  m_l_tibia: 0.0 0.0 0.0
  m_l_tarsus: 0.0 0.0 0.0
  m_l_claws: 0.0 0.0 0.0
  m_r_coxa: 0.0 0.0 0.0
  m_r_trochanter: 0.0 0.0 0.0
  m_r_femur: 0.0 0.0 0.0
  m_r_tibia: 0.0 0.0 0.0
  m_r_tarsus: 0.0 0.0 0.0
  m_r_claws: 0.0 0.0 0.0
  h_l_coxa: 0.0 0.0 0.0
  h_l_trochanter: 0.0 0.0 0.0
  h_l_femur: 0.0 0.0 0.0
  h_l_tibia: 0.0 0.0 0.0
  h_l_tarsus: 0.0 0.0 0.0
  h_l_claws: 0.0 0.0 0.0
  h_r_coxa: 0.0 0.0 0.0
  h_r_trochanter: 0.0 0.0 0.0
  h_r_femur: 0.0 0.0 0.0
  h_r_tibia: 0.0 0.0 0.0
  h_r_tarsus: 0.0 0.0 0.0
  h_r_claws: 0.0 0.0 0.0

KEYPOINT_MODEL_PAIRS:
  mouth: 04-t1-l
  head: reference_base
  head_t1: 04-t1-l
  t1_t2: 05-t2-l
  t2_t3: 06-t3-l
  t3_a1: 07-a2-l
  a2_a3: 08-a3-l
  a4_a5: 10-a5-l
  a6_a7: 12-a7-l
  a8_end: 14-a9-l
  r_antenna_base: 04-t1-l
  r_antenna_tip: reference_base
  l_antenna_base: 04-t1-l
  l_antenna_tip: reference_base
  f_l_coxa: 16-f-l-coxa-l
  f_l_trochanter: 17-f-l-femur-l
  f_l_femur: 17-f-l-femur-l
  f_l_tibia: 18-f-l-tibia-l
  f_l_tarsus: 19-f-l-tarsus-l
  f_l_claws: 20-f-l-claws-l
  f_r_coxa: 31-f-r-coxa-l
  f_r_trochanter: 32-f-r-femur-l
  f_r_femur: 32-f-r-femur-l
  f_r_tibia: 33-f-r-tibia-l
  f_r_tarsus: 35-f-r-tarsus-l
  f_r_claws: 36-f-r-claws-l
  m_l_coxa: 21-m-l-coxa-l
  m_l_trochanter: 22-m-l-femur-l
  m_l_femur: 22-m-l-femur-l
  m_l_tibia: 23-m-l-tibia-l
  m_l_tarsus: 24-m-l-tarsus-l
  m_l_claws: 25-m-l-claws-l
  m_r_coxa: 37-m-r-coxa-l
  m_r_trochanter: 38-m-r-femur-l
  m_r_femur: 38-m-r-femur-l
  m_r_tibia: 39-m-r-tibia-l
  m_r_tarsus: 40-m-r-tarsus-l
  m_r_claws: 41-m-r-claws-l
  h_l_coxa: 26-h-l-coxa-l
  h_l_trochanter: 27-h-l-femur-l
  h_l_femur: 27-h-l-femur-l
  h_l_tibia: 28-h-l-tibia-l
  h_l_tarsus: 29-h-l-tarsus-l
  h_l_claws: 30-h-l-claws-l
  h_r_coxa: 42-h-r-coxa-l
  h_r_trochanter: 43-h-r-femur-l
  h_r_femur: 43-h-r-femur-l
  h_r_tibia: 44-h-r-tibia-l
  h_r_tarsus: 45-h-r-tarsus-l
  h_r_claws: 46-h-r-claws-l

KP_NAMES:
  - mouth
  - head
  - head_t1
  - t1_t2
  - t2_t3
  - t3_a1
  - a2_a3
  - a4_a5
  - a6_a7
  - a8_end
  - r_antenna_base
  - r_antenna_tip
  - l_antenna_base
  - l_antenna_tip
  - f_l_coxa
  - f_l_trochanter
  - f_l_femur
  - f_l_tibia
  - f_l_tarsus
  - f_l_claws
  - f_r_coxa
  - f_r_trochanter
  - f_r_femur
  - f_r_tibia
  - f_r_tarsus
  - f_r_claws
  - m_l_coxa
  - m_l_trochanter
  - m_l_femur
  - m_l_tibia
  - m_l_tarsus
  - m_l_claws
  - m_r_coxa
  - m_r_trochanter
  - m_r_femur
  - m_r_tibia
  - m_r_tarsus
  - m_r_claws
  - h_l_coxa
  - h_l_trochanter
  - h_l_femur
  - h_l_tibia
  - h_l_tarsus
  - h_l_claws
  - h_r_coxa
  - h_r_trochanter
  - h_r_femur
  - h_r_tibia
  - h_r_tarsus
  - h_r_claws

SCALE_FACTOR: 1

MOCAP_SCALE_FACTOR: 0.0013

RENDER_FPS: 25

N_SAMPLE_FRAMES: 100

#TRUNK_OPTIMIZATION_KEYPOINTS: []

M_REG_COEF: 1

TRUNK_OPTIMIZATION_KEYPOINTS:
  - t1_t2
  - t2_t3
  - t3_a1
  - a2_a3
  - a4_a5
  - a6_a7
  - a8_end

#ROOT_OPTIMIZATION_KEYPOINT: "head_t1"
ROOT_OPTIMIZATION_KEYPOINT: "t2_t3"


KEYPOINT_COLOR_PAIRS:
  mouth: .3 0 0 1
  head: .3 0 0 1
  head_t1: .3 0 0 1
  t1_t2: .3 0 0 1
  t2_t3: .3 0 0 1
  t3_a1: .3 0 0 1
  a2_a3: .3 0 0 1
  a4_a5: .3 0 0 1
  a6_a7: .3 0 0 1
  a8_end: .3 0 0 1
  r_antenna_base: .3 0 0 1
  r_antenna_tip: .3 0 0 1
  l_antenna_base: .3 0 0 1
  l_antenna_tip: .3 0 0 1
  f_l_coxa: 0 0 .3 1
  f_l_trochanter: 0 0 .3 1
  f_l_femur: 0 0 .3 1
  f_l_tibia: 0 0 .3 1
  f_l_tarsus: 0 0 .3 1
  f_l_claws: 0 0 .3 1
  f_r_coxa: 0 0 .3 1
  f_r_trochanter: 0 0 .3 1
  f_r_femur: 0 0 .3 1
  f_r_tibia: 0 0 .3 1
  f_r_tarsus: 0 0 .3 1
  f_r_claws: 0 0 .3 1
  m_l_coxa: 0 0 .3 1
  m_l_trochanter: 0 0 .3 1
  m_l_femur: 0 0 .3 1
  m_l_tibia: 0 0 .3 1
  m_l_tarsus: 0 0 .3 1
  m_l_claws: 0 0 .3 1
  m_r_coxa: 0 0 .3 1
  m_r_trochanter: 0 0 .3 1
  m_r_femur: 0 0 .3 1
  m_r_tibia: 0 0 .3 1
  m_r_tarsus: 0 0 .3 1
  m_r_claws: 0 0 .3 1
  h_l_coxa: 0 0 .3 1
  h_l_trochanter: 0 0 .3 1
  h_l_femur: 0 0 .3 1
  h_l_tibia: 0 0 .3 1
  h_l_tarsus: 0 0 .3 1
  h_l_claws: 0 0 .3 1
  h_r_coxa: 0 0 .3 1
  h_r_trochanter: 0 0 .3 1
  h_r_femur: 0 0 .3 1
  h_r_tibia: 0 0 .3 1
  h_r_tarsus: 0 0 .3 1
  h_r_claws: 0 0 .3 1

INDIVIDUAL_PART_OPTIMIZATION:
  "f_r_leg": [
    "31-f-r-coxa-l",  
    "32-f-r-femur-l", 
    "33-f-r-tibia-l", 
    "35-f-r-tarsus-l", 
    "36-f-r-claws-l"
  ]
  "f_l_leg": [
    "16-f-l-coxa-l",
    "17-f-l-femur-l", 
    "18-f-l-tibia-l", 
    "19-f-l-tarsus-l", 
    "20-f-l-claws-l"
  ]
  m_r_leg: [
    37-m-r-coxa-l,
    38-m-r-femur-l,
    39-m-r-tibia-l,
    40-m-r-tarsus-l,
    41-m-r-claws-l
  ]

  m_l_leg: [
    21-m-l-coxa-l,
    22-m-l-femur-l,
    23-m-l-tibia-l,
    24-m-l-tarsus-l,
    25-m-l-claws-l
  ]

  h_r_leg: [
    42-h-r-coxa-l,
    43-h-r-femur-l,
    44-h-r-tibia-l,
    45-h-r-tarsus-l,
    46-h-r-claws-l
  ]

  h_l_leg: [
    26-h-l-coxa-l,
    27-h-l-femur-l,
    28-h-l-tibia-l,
    29-h-l-tarsus-l,
    30-h-l-claws-l
  ]

  head: [
    04-t1-l,
    reference_base,
  ]

SITES_TO_REGULARIZE:
- mouth
- head
- head_t1
- l_antenna_base
- r_antenna_base
- t1_t2
- t2_t3
- t3_a1
- a2_a3
- a4_a5
- a6_a7
- a8_end