fit_offsets_path: "Fruitfly_fit_V1_free2.h5"
ik_only_path: "Fruitfly_ik_V1_free2.h5"

data_path: "/data/users/eabe/biomech_model/Flybody/datasets/Johnsonlab/example_bout_1.h5"
save_path: "/data/users/eabe/biomech_model/Flybody/datasets/Johnsonlab/"

continuous: False
enable_padding: True
n_fit_frames: 601
n_frames_per_clip: 300
skip_fit_offsets: False
skip_ik_only: False
infer_qvels: True 

mujoco:
  solver: "cg"
  iterations: 1
  ls_iterations: 4
  dt: 0.00333
