fit_offsets_path: "Fruitfly_V1_fit.h5"
ik_only_path: "Fruitfly_V1_ik.h5"

data_path: "/data/users/eabe/biomech_model/Flybody/datasets/Tuthill_data/New_aligned_Walking_V2_avg.h5"
save_path: "/data/users/eabe/biomech_model/Flybody/datasets/Tuthill_data/"

n_fit_frames: 601
n_frames_per_clip: 300
skip_fit_offsets: True
skip_ik_only: False
infer_qvels: True 
continuous: True
enable_padding: True

mujoco:
  solver: "cg"
  iterations: 1
  ls_iterations: 4
  dt: 0.00333
