fit_offsets_path: "stick_fit_offsets.h5"
ik_only_path: "stick_ik_only.h5"
data_path: "/root/vast/rusham/GitRepos/stac-keypoints-ui/stac_keypoints_ui/data/014_h_offset.csv"

n_fit_frames: 250
skip_fit_offsets: False
skip_ik_only: True
infer_qvels: True # Infer qvels from stac output
n_frames_per_clip: 125 # 1 if mocap is one session

mujoco:
  solver: "newton"
  iterations: 1
  ls_iterations: 4